
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeliveryWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://msw0068:8090/soap/delivery-service?WSDL")
public class DeliveryWebService
    extends Service
{

    private final static URL DELIVERYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYWEBSERVICE_EXCEPTION;
    private final static QName DELIVERYWEBSERVICE_QNAME = new QName("http://tempuri.org/", "DeliveryWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://msw0068:8090/soap/delivery-service?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYWEBSERVICE_WSDL_LOCATION = url;
        DELIVERYWEBSERVICE_EXCEPTION = e;
    }

    public DeliveryWebService() {
        super(__getWsdlLocation(), DELIVERYWEBSERVICE_QNAME);
    }

    public DeliveryWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYWEBSERVICE_QNAME, features);
    }

    public DeliveryWebService(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYWEBSERVICE_QNAME);
    }

    public DeliveryWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYWEBSERVICE_QNAME, features);
    }

    public DeliveryWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDeliveryWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDeliveryWebService")
    public IDeliveryWebService getBasicHttpBindingIDeliveryWebService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDeliveryWebService"), IDeliveryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDeliveryWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDeliveryWebService")
    public IDeliveryWebService getBasicHttpBindingIDeliveryWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDeliveryWebService"), IDeliveryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYWEBSERVICE_EXCEPTION!= null) {
            throw DELIVERYWEBSERVICE_EXCEPTION;
        }
        return DELIVERYWEBSERVICE_WSDL_LOCATION;
    }

}
